server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_management_system_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_DEF_USER}
    password: ${DB_DEF_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor: WARN
      nodeValue: WARN


mail:
  host: "localhost"
  port: 1025
  username: "task-management-sytem@tms-group.bg"
  password: ""